C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-1-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-1-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-1-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-1-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-1-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-1-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-1-even.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-2-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-2-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-2-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-2-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-2-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-2-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-2-even.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-3-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-3-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-3-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-3-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-3-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-3-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-3-even.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-even-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-even-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-even-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-even-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-even-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-even-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 1-even-even.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-1-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-1-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-1-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-1-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-1-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-1-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-1-even.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-2-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-2-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-2-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-2-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-2-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-2-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-2-even.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-3-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-3-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-3-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-3-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-3-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-3-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-3-even.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-even-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-even-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-even-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-even-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-even-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-even-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 2-even-even.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-1-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-1-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-1-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-1-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-1-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-1-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-1-even.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-2-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-2-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-2-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-2-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-2-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-2-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-2-even.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-3-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-3-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-3-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-3-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-3-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-3-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-3-even.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-even-1.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-even-2.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-even-3.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-even-4.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-even-5.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-even-6.txt
C:\Users\Luc\AppData\Local\Programs\Python\Python37\python.exe dionyssus.py 3-even-even.txt
